//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articleInfo
    {
        public int articleId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> areaId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> visitedNum { get; set; }
        public Nullable<int> isEnable { get; set; }
    
        public virtual areaInfo areaInfo { get; set; }
        public virtual userInfo userInfo { get; set; }
    }
}
